import { EventCategory, Division } from '@/types/drill';

export interface CriteriaDefinition {
  id: string;
  seqNumber: number;
  category: EventCategory;
  division?: Division;
  name: string;
  description: string;
  maxPoints: number;
  isPauseCommand?: boolean;
  isHeadJudgeSpecial?: 'knowledge' | 'uniform';
}

export const DRILL_CRITERIA: CriteriaDefinition[] = [
  {
    id: 'armed_reg_01',
    seqNumber: 1,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Forward March (Entrance)*",
    description: "Enter drill floor together in military fashion, front/center on Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_02',
    seqNumber: 2,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Inspection, Port, Order Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_03',
    seqNumber: 3,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Verbal Report In",
    description: "Commander reports in verbally to Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_04',
    seqNumber: 4,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Attention",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_05',
    seqNumber: 5,
    category: 'REGULATION',
    division: 'ARMED',
    name: "15 Count Manual of Arms**",
    description: "Right shoulder, Left shoulder, Present arms, Order arms in standard cadence",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_06',
    seqNumber: 6,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Count Off",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_07',
    seqNumber: 7,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Open Ranks, March",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_08',
    seqNumber: 8,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Close Ranks, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_09',
    seqNumber: 9,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left Step, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_10',
    seqNumber: 10,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_11',
    seqNumber: 11,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left, Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_12',
    seqNumber: 12,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Right Step, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_13',
    seqNumber: 13,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_14',
    seqNumber: 14,
    category: 'REGULATION',
    division: 'ARMED',
    name: "About, Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_15',
    seqNumber: 15,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Right Shoulder, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_16',
    seqNumber: 16,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Forward, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_17',
    seqNumber: 17,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Right, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_18',
    seqNumber: 18,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Right, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_19',
    seqNumber: 19,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Right, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_20',
    seqNumber: 20,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left Flank, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_21',
    seqNumber: 21,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Right Flank, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_22',
    seqNumber: 22,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_23',
    seqNumber: 23,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_24',
    seqNumber: 24,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Rear, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_25',
    seqNumber: 25,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Rear, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_26',
    seqNumber: 26,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Close Interval, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_27',
    seqNumber: 27,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Normal Interval, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_28',
    seqNumber: 28,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_29',
    seqNumber: 29,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Port, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_30',
    seqNumber: 30,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_31',
    seqNumber: 31,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Change Step, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_32',
    seqNumber: 32,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Mark Time, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_33',
    seqNumber: 33,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Forward, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_34',
    seqNumber: 34,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_35',
    seqNumber: 35,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Right Shoulder, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_36',
    seqNumber: 36,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_37',
    seqNumber: 37,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_38',
    seqNumber: 38,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_39',
    seqNumber: 39,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column 1/2 Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_40',
    seqNumber: 40,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column 1/2 Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_41',
    seqNumber: 41,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Rear, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_42',
    seqNumber: 42,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Rear, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_43',
    seqNumber: 43,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_44',
    seqNumber: 44,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_45',
    seqNumber: 45,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Eyes Right",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_46',
    seqNumber: 46,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Ready, Front",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_47',
    seqNumber: 47,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_48',
    seqNumber: 48,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left Shoulder, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_49',
    seqNumber: 49,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Column Left, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_50',
    seqNumber: 50,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left Flank, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_51',
    seqNumber: 51,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Right Flank, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_52',
    seqNumber: 52,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'armed_reg_53',
    seqNumber: 53,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Order, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_54',
    seqNumber: 54,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Left, Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_55',
    seqNumber: 55,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Verbal Report Out***",
    description: "Verbally report out to Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'armed_reg_56',
    seqNumber: 56,
    category: 'REGULATION',
    division: 'ARMED',
    name: "Depart Drill Floor",
    description: "Depart drill floor in precise military manner",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_01',
    seqNumber: 1,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March (Entrance)*",
    description: "Enter drill floor together in military fashion, front/center on Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_02',
    seqNumber: 2,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Report In (VERBAL)",
    description: "Commander reports in verbally to Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_03',
    seqNumber: 3,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Parade Rest",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_04',
    seqNumber: 4,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Attention",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_05',
    seqNumber: 5,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Present Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_06',
    seqNumber: 6,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Order, Arms",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_07',
    seqNumber: 7,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Count Off",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_08',
    seqNumber: 8,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Close Interval, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_09',
    seqNumber: 9,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Normal Interval, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_10',
    seqNumber: 10,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Right Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_11',
    seqNumber: 11,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_12',
    seqNumber: 12,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Open Ranks March",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_13',
    seqNumber: 13,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Close Ranks, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_14',
    seqNumber: 14,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Step March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_15',
    seqNumber: 15,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_16',
    seqNumber: 16,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_17',
    seqNumber: 17,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Right Step March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_18',
    seqNumber: 18,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon, Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_19',
    seqNumber: 19,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "About Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_20',
    seqNumber: 20,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_21',
    seqNumber: 21,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Right March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_22',
    seqNumber: 22,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Right March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_23',
    seqNumber: 23,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Right March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_24',
    seqNumber: 24,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Flank, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_25',
    seqNumber: 25,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Right Flank March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_26',
    seqNumber: 26,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_27',
    seqNumber: 27,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_28',
    seqNumber: 28,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Rear March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_29',
    seqNumber: 29,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Rear March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_30',
    seqNumber: 30,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Close Interval March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_31',
    seqNumber: 31,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_32',
    seqNumber: 32,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Normal Interval, March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_33',
    seqNumber: 33,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_34',
    seqNumber: 34,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_35',
    seqNumber: 35,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Change Step March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_36',
    seqNumber: 36,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Mark Time March",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_37',
    seqNumber: 37,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon Halt",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_38',
    seqNumber: 38,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_39',
    seqNumber: 39,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_40',
    seqNumber: 40,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Change Step March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_41',
    seqNumber: 41,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_42',
    seqNumber: 42,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_43',
    seqNumber: 43,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column 1/2 Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_44',
    seqNumber: 44,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column 1/2 Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_45',
    seqNumber: 45,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Rear March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_46',
    seqNumber: 46,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Rear March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_47',
    seqNumber: 47,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_48',
    seqNumber: 48,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_49',
    seqNumber: 49,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Eyes Right",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_50',
    seqNumber: 50,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Ready Front",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_51',
    seqNumber: 51,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left march",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_52',
    seqNumber: 52,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Half Step March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_53',
    seqNumber: 53,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Forward March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_54',
    seqNumber: 54,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Column Left March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_55',
    seqNumber: 55,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Flank March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_56',
    seqNumber: 56,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Right Flank March",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_57',
    seqNumber: 57,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Platoon Halt",
    description: "5-Second Pause",
    maxPoints: 5,
    isPauseCommand: true,
  },
  {
    id: 'unarmed_reg_58',
    seqNumber: 58,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Left Face",
    description: "",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_59',
    seqNumber: 59,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Report Out",
    description: "Verbally report out to Head Judge",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'unarmed_reg_60',
    seqNumber: 60,
    category: 'REGULATION',
    division: 'UNARMED',
    name: "Depart the Drill Floor",
    description: "Depart drill floor in precise military manner",
    maxPoints: 5,
    isPauseCommand: false,
  },
  {
    id: 'cg_01',
    seqNumber: 1,
    category: 'COLOR_GUARD',
    name: "Sling Arms",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_02',
    seqNumber: 2,
    category: 'COLOR_GUARD',
    name: "Post",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_03',
    seqNumber: 3,
    category: 'COLOR_GUARD',
    name: "Uncase the Colors",
    description: "Proper sequence: Sling Arms, Post, Uncase, Present/Order, Post",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_04',
    seqNumber: 4,
    category: 'COLOR_GUARD',
    name: "Present Arms/Order Arms",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_05',
    seqNumber: 5,
    category: 'COLOR_GUARD',
    name: "Post",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_06',
    seqNumber: 6,
    category: 'COLOR_GUARD',
    name: "Report In",
    description: "Report in centered on Head Judge, 6 paces away",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_07',
    seqNumber: 7,
    category: 'COLOR_GUARD',
    name: "Colors Reverse March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_08',
    seqNumber: 8,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_09',
    seqNumber: 9,
    category: 'COLOR_GUARD',
    name: "Left Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_10',
    seqNumber: 10,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_11',
    seqNumber: 11,
    category: 'COLOR_GUARD',
    name: "Colors Reverse March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_12',
    seqNumber: 12,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_13',
    seqNumber: 13,
    category: 'COLOR_GUARD',
    name: "Color Guard Halt",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_14',
    seqNumber: 14,
    category: 'COLOR_GUARD',
    name: "Mark Time, March (5 Seconds)",
    description: "Hold mark time for 5 seconds",
    maxPoints: 10,
    isPauseCommand: true,
  },
  {
    id: 'cg_15',
    seqNumber: 15,
    category: 'COLOR_GUARD',
    name: "COLOR GUARD, HALT",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_16',
    seqNumber: 16,
    category: 'COLOR_GUARD',
    name: "Order Colors",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_17',
    seqNumber: 17,
    category: 'COLOR_GUARD',
    name: "Parade Rest",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_18',
    seqNumber: 18,
    category: 'COLOR_GUARD',
    name: "Colors Guard, Attention",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_19',
    seqNumber: 19,
    category: 'COLOR_GUARD',
    name: "CARRY COLORS",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_20',
    seqNumber: 20,
    category: 'COLOR_GUARD',
    name: "Forward March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_21',
    seqNumber: 21,
    category: 'COLOR_GUARD',
    name: "Right Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_22',
    seqNumber: 22,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_23',
    seqNumber: 23,
    category: 'COLOR_GUARD',
    name: "Right Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_24',
    seqNumber: 24,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_25',
    seqNumber: 25,
    category: 'COLOR_GUARD',
    name: "Colors Reverse March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_26',
    seqNumber: 26,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_27',
    seqNumber: 27,
    category: 'COLOR_GUARD',
    name: "Eyes Right",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_28',
    seqNumber: 28,
    category: 'COLOR_GUARD',
    name: "Ready Front",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_29',
    seqNumber: 29,
    category: 'COLOR_GUARD',
    name: "Left Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_30',
    seqNumber: 30,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_31',
    seqNumber: 31,
    category: 'COLOR_GUARD',
    name: "Left Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_32',
    seqNumber: 32,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_33',
    seqNumber: 33,
    category: 'COLOR_GUARD',
    name: "Left Wheel March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_34',
    seqNumber: 34,
    category: 'COLOR_GUARD',
    name: "Forward, March",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_35',
    seqNumber: 35,
    category: 'COLOR_GUARD',
    name: "Color Guard, Halt",
    description: "",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_36',
    seqNumber: 36,
    category: 'COLOR_GUARD',
    name: "Report Out",
    description: "Verbally report out to Head Judge",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'cg_37',
    seqNumber: 37,
    category: 'COLOR_GUARD',
    name: "Overall Technical Score",
    description: "Technical execution and alignment (0-25 pts)",
    maxPoints: 25,
    isPauseCommand: false,
  },
  {
    id: 'cg_38',
    seqNumber: 38,
    category: 'COLOR_GUARD',
    name: "Overall Precision Score",
    description: "Unison, cadence, and bearing (0-25 pts)",
    maxPoints: 25,
    isPauseCommand: false,
  },
  {
    id: 'exh_01',
    seqNumber: 1,
    category: 'EXHIBITION',
    division: undefined,
    name: "Originality & Showmanship",
    description: "Creative choreography, dynamic sequences, unique squad formations",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_02',
    seqNumber: 2,
    category: 'EXHIBITION',
    division: undefined,
    name: "Precision & Uniformity",
    description: "Pinpoint coordination, uniform angles, instantaneous stops, and unison clicks",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_03',
    seqNumber: 3,
    category: 'EXHIBITION',
    division: undefined,
    name: "Movement Complexity & Difficulty",
    description: "High-risk exchanges, rapid direction reversals, intricate sequential ripples",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_04',
    seqNumber: 4,
    category: 'EXHIBITION',
    division: undefined,
    name: "Military Bearing & Flavor",
    description: "Routines adhere to military dignity without inappropriate street or dance elements",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_05',
    seqNumber: 5,
    category: 'EXHIBITION',
    division: undefined,
    name: "Cadence Variation & Step Dynamics",
    description: "Mastery of slow-time, quick-time, double-time, and silent footwork",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_06',
    seqNumber: 6,
    category: 'EXHIBITION',
    division: 'ARMED',
    name: "Rifle Spins & Toss Sharpness (Armed)",
    description: "Clean handoffs, spinning velocity, overhead tosses, and flawless recovery",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_07',
    seqNumber: 7,
    category: 'EXHIBITION',
    division: undefined,
    name: "Floor Coverage & Boundary Control",
    description: "Utilizing all drill pad sectors effectively without boundary line violations",
    maxPoints: 10,
    isPauseCommand: false,
  },
  {
    id: 'exh_08',
    seqNumber: 8,
    category: 'EXHIBITION',
    division: undefined,
    name: "Report In & Report Out Execution",
    description: "Crisp military salute and report formulation at start and finish within time window",
    maxPoints: 10,
    isPauseCommand: false,
  },
];

export function getCriteriaForEvent(category: EventCategory, division?: Division): CriteriaDefinition[] {
  return DRILL_CRITERIA.filter((c) => {
    if (c.category !== category) return false;
    if (c.division && division && c.division !== division) return false;
    return true;
  });
}
